### ISSUE TITLE
Firmware update via web interface

### ISSUE THREAD

**Issue by duelago** [bofh69/AiLight#11]
We have to provide non geeks with a simple way to update the firmware via the web interface.
Solution here?
http://esp8266.github.io/Arduino/versions/2.0.0/doc/ota_updates/ota_updates.html#web-browser

**Comment by bofh69** [comment]
It isn't compatible with the other webserver that is used.

I made another solution instead.
20 seconds after starting/rebooting it will check a webserver for an updated firmware. The URL is something like:
http://HOST/PATH/from-CURRENT_VERSION/firmware.bin

If there is no file there, it will continue as usual, otherwise it will upgrade to it and reboot.

There is code for it in _ota.ino now, but I've commented it out for the time being.

**Comment by bofh69** [comment]
Its implemented now.
